package com.example.brightbuds_app.services;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.util.Log;

import com.example.brightbuds_app.models.Progress;
import com.example.brightbuds_app.utils.EncryptionUtil;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.List;

public class PDFReportService {

    private static final String TAG = "PDFReportService";
    private final Context context;
    private long startTimestamp = 0;
    private long endTimestamp = 0;

    public interface PDFCallback {
        void onSuccess(String filePath);
        void onFailure(Exception e);
    }

    public PDFReportService(Context context) { this.context = context; }

    public void setDateRange(long start, long end) { this.startTimestamp = start; this.endTimestamp = end; }

    /** ADMIN REPORT */
    public void generateAdminProgressReport(List<Progress> list, double avg, int total,
                                            String generatedBy, Map<String, String> childNames,
                                            Map<String, String> parentNames, PDFCallback cb) {
        File file = createReportFile("BrightBuds_Admin_Report");
        if (file == null) { cb.onFailure(new IOException("Cannot create file")); return; }

        try (FileOutputStream out = new FileOutputStream(file)) {
            Document doc = new Document();
            PdfWriter.getInstance(doc, out);
            doc.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font font = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font small = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.DARK_GRAY);

            Paragraph title = new Paragraph("BrightBuds System Progress Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);
            doc.add(new Paragraph("Generated by: " + generatedBy, font));
            doc.add(new Paragraph("Generated on: " + new SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault()).format(new Date()), font));
            doc.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            addTableHeader(table, new String[]{"Child", "Parent", "Modules", "Avg Score"});

            Map<String, List<Progress>> grouped = new HashMap<>();
            for (Progress p : list)
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    grouped.computeIfAbsent(p.getChildId(), k -> new ArrayList<>()).add(p);
                }

            for (var entry : grouped.entrySet()) {
                String childId = entry.getKey();
                List<Progress> pl = entry.getValue();
                String childName = null;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    childName = decryptChildName(childNames.getOrDefault(childId, "Child"));
                }
                String parentName = null;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    parentName = decryptParentName(parentNames.getOrDefault(pl.get(0).getParentId(), "Parent"));
                }
                double cAvg = 0;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    cAvg = pl.stream().mapToDouble(Progress::getScore).average().orElse(0);
                }
                addDetailedRow(table, childName, parentName, String.valueOf(pl.size()),
                        String.format(Locale.getDefault(), "%.1f%%", cAvg), BaseColor.WHITE, font);
            }

            doc.add(table);
            doc.add(new Paragraph("\nGenerated automatically by BrightBuds App", small));
            doc.close();

            cb.onSuccess(file.getAbsolutePath());
        } catch (Exception e) {
            cb.onFailure(e);
        }
    }

    /** PARENT REPORT */
    public void generateProgressReport(List<Progress> list, double avg, int total,
                                       String parentName, Map<String, String> childNames, PDFCallback cb) {
        File file = createReportFile("BrightBuds_Family_Report");
        if (file == null) { cb.onFailure(new IOException("Cannot create file")); return; }

        try (FileOutputStream out = new FileOutputStream(file)) {
            Document doc = new Document();
            PdfWriter.getInstance(doc, out);
            doc.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font font = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font bold = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font small = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.DARK_GRAY);

            Paragraph title = new Paragraph("BrightBuds Learning Progress Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);
            doc.add(new Paragraph("Parent: " + parentName, font));
            doc.add(new Paragraph("Generated on: " + new SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault()).format(new Date()), font));
            doc.add(new Paragraph(" "));

            PdfPTable summary = new PdfPTable(3);
            summary.setWidthPercentage(100);
            addTableHeader(summary, new String[]{"Child", "Modules Completed", "Average Score"});

            Map<String, List<Progress>> grouped = new HashMap<>();
            for (Progress p : list)
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    grouped.computeIfAbsent(p.getChildId(), k -> new ArrayList<>()).add(p);
                }

            for (var entry : grouped.entrySet()) {
                String childId = entry.getKey();
                List<Progress> progress = entry.getValue();
                String child = null;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    child = decryptChildName(childNames.getOrDefault(childId, "Child"));
                }
                double cAvg = 0;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    cAvg = progress.stream().mapToDouble(Progress::getScore).average().orElse(0);
                }
                addSummaryRow(summary, child, String.valueOf(progress.size()),
                        String.format(Locale.getDefault(), "%.1f%%", cAvg), BaseColor.WHITE, font);
            }

            doc.add(summary);
            doc.add(new Paragraph("\nDetailed Progress by Child", headerFont));
            doc.add(new Paragraph(" "));

            for (var child : grouped.entrySet()) {
                String childId = child.getKey();
                String cName = null;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    cName = decryptChildName(childNames.getOrDefault(childId, "Child"));
                }
                doc.add(new Paragraph("Child: " + cName, bold));

                PdfPTable childTable = new PdfPTable(3);
                childTable.setWidthPercentage(100);
                addTableHeader(childTable, new String[]{"Module", "Status", "Times Played"});

                Map<String, List<Progress>> modMap = new HashMap<>();
                for (Progress p : child.getValue())
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                        modMap.computeIfAbsent(getModuleName(p), k -> new ArrayList<>()).add(p);
                    }

                for (var mod : modMap.entrySet()) {
                    String module = mod.getKey();
                    List<Progress> pl = mod.getValue();
                    String status = null;
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                        status = pl.stream().map(Progress::getStatus).filter(Objects::nonNull).findFirst().orElse("Completed");
                    }
                    addDetailedRow(childTable, module, status, String.valueOf(pl.size()), BaseColor.WHITE, font);
                }
                doc.add(childTable);
                doc.add(new Paragraph(" "));
            }

            doc.add(new Paragraph("© 2025 BrightBuds Learning Platform", small));
            doc.close();

            cb.onSuccess(file.getAbsolutePath());
        } catch (Exception e) {
            cb.onFailure(e);
        }
    }

    /** HELPERS  */
    private String decryptChildName(String val) {
        String dec = EncryptionUtil.decrypt(val);
        return (dec != null && !dec.isEmpty()) ? dec : val;
    }

    private String decryptParentName(String val) {
        String dec = EncryptionUtil.decrypt(val);
        return (dec != null && !dec.isEmpty()) ? dec : val;
    }

    private String getModuleName(Progress p) {
        String id = p.getModuleId();
        if (id == null) return "Unknown Module";
        switch (id) {
            case "module_abc_song": return "ABC Song";
            case "module_123_song": return "123 Song";
            case "module_feed_the_monster": return "Feed the Monster";
            case "module_match_the_letter": return "Match the Letter";
            case "module_memory_match": return "Memory Match";
            case "module_word_builder": return "Word Builder";
            case "module_my_family": return "My Family Album";
            default:
                String dec = EncryptionUtil.decrypt(id);
                return (dec != null && !dec.isEmpty()) ? dec : id;
        }
    }

    private String generateDefaultModuleName(Progress p) {
        if (p.getScore() >= 90) return "Excellent Activity";
        if (p.getScore() >= 70) return "Good Activity";
        return "Learning Activity";
    }

    private File createReportFile(String prefix) {
        String name = prefix + "_" + new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(new Date()) + ".pdf";
        File dir = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
                ? new File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "BrightBudsReports")
                : new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS), "BrightBudsReports");
        if (!dir.exists()) dir.mkdirs();
        return new File(dir, name);
    }

    private void addSummaryRow(PdfPTable t, String a, String b, String c, BaseColor bg, Font f) {
        PdfPCell[] cells = {
                new PdfPCell(new Phrase(a, f)),
                new PdfPCell(new Phrase(b, f)),
                new PdfPCell(new Phrase(c, f))
        };
        for (PdfPCell cell : cells) {
            cell.setBackgroundColor(bg);
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setNoWrap(false);
            t.addCell(cell);
        }
    }

    private void addDetailedRow(PdfPTable t, String a, String b, String c, BaseColor bg, Font f) {
        PdfPCell[] cells = {
                new PdfPCell(new Phrase(a, f)),
                new PdfPCell(new Phrase(b, f)),
                new PdfPCell(new Phrase(c, f))
        };
        for (PdfPCell cell : cells) {
            cell.setBackgroundColor(bg);
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setNoWrap(false);
            t.addCell(cell);
        }
    }

    private void addDetailedRow(PdfPTable t, String a, String b, String c, String d, BaseColor bg, Font f) {
        PdfPCell[] cells = {
                new PdfPCell(new Phrase(a, f)),
                new PdfPCell(new Phrase(b, f)),
                new PdfPCell(new Phrase(c, f)),
                new PdfPCell(new Phrase(d, f))
        };
        for (PdfPCell cell : cells) {
            cell.setBackgroundColor(bg);
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setNoWrap(false);
            t.addCell(cell);
        }
    }

    private void addTableHeader(PdfPTable t, String[] headers) {
        BaseColor color = new BaseColor(70, 130, 180);
        Font f = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.WHITE);
        for (String h : headers) {
            PdfPCell c = new PdfPCell(new Phrase(h, f));
            c.setBackgroundColor(color);
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            c.setPadding(7);
            t.addCell(c);
        }
    }
}
